### PR TITLE
Added functions for Google Sheets

### LINKED ISSUE #22: (1.2.0.0) Export-GDriveItemContent function is missing from module manifest
In v1.2.0.0 the _Export-GDriveItemContent()_ function isn't declared in the module manifest, so when you import the module that function can't be found.

Manually editing the _GMGoogleDrive.psd1_ manifest file and adding this function to the _FunctionsToExport_ hashtable fixes the issue and exposes the function after re-importing the module.

### PR DESCRIPTION
**Pull request by elhaus**
This pull request added the functions
- Add-GSheetsSheet
- Remove-GSheetsSheet
- Clear-GSheetsValue
- Get-GSheetsValue
- Set-GSheetsValue
- Convert-A1NotationToGridRange
- Export-GSheets
- Get-GSheetsSpreadsheet
- Set-GSheetsFormatting

From my perspective the most powerfull command is Export-GSheets. Export-GSheets can be compared with Export-Csv

In addition I added the a GitHub action for PSScriptAnalyzer. PSScriptAnalyzer is a static code analyzer that reports potential code defects and suggests possible solutions for improvements.
Some suggestions from PSScriptAnalyzer are also included in the pull request. (like AvoidTrailingWhitespace)

I also implemented the change suggested in #22 
fixes #22

I'm open to discuss the new functions.
If you have any ideas for additional functions for Google Sheets please let me know.

### CODE REVIEW

**Comment by MVKozlov** [comment]
I haven't had a chance to use gsheets yet :)
I'll look at it a bit later

**Comment by MVKozlov** [comment]
looked, but haven't tried it yet

Great contribution.

Just a few changes:
`Set-GSheetsFormatting` and `Get-GSheetsSpreadsheet` have incomplete descriptions/examples

`Export-GSheets` is questionable. Shouldn't it be `Export-GSheetsSpreadsheet` ?

And in it, the values ​​are collected into an array as `$Values ​​+= @(,$Row)`
Which is considered not a very good practice for arrays and expensive in memory. For values ​​of 1000 and more, you get unacceptable overhead
It would be good to replace it with an ArrayList or something similar

**Comment by elhaus** [comment]
I added the description and examples for the two functions you mentioned.

Regarding `$Values ​​+= @(,$Row)`: Google Sheets API requires a two dimensional array. The other options I tried, PowerShell combined the arrays to a one dimensional array. I will check again if I can find another solution. If you have already an idea, please let me know.

**Comment by MVKozlov** [comment]
`Add-GSheetsSheet.ps1` named as `New-GSheetsSheet` function inside so it not available
and there is no method to [create new GoogleSheet](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/create)

**Comment by MVKozlov** [comment]
Remove- cmdlets should have `ConfirmImpact='High'`
And I think we need also
`New-GSheetsSpreadSheet`, `Remove-GSheetsSpreadSheet` to cover SpreadSheet area

**Comment by MVKozlov** [comment]
> Regarding `$Values ​​+= @(,$Row)`: Google Sheets API requires a two dimensional array. The other options I tried, PowerShell combined the arrays to a one dimensional array.

I mean only `array += value` syntax. anyway, default `$TransferLines` is far enough from the limit beyond which the performance degradation begins to appear

**Pull request merged**
